### ISSUE TITLE
Please consider to transfer the ownership of npm package

### ISSUE THREAD

**Issue by cocopon** [1se/hyper-iceberg#1]
Hello, I’m an original author of Iceberg. Thank you for loving and porting it!

Recently I received a question about Iceberg theme for Hyper terminal:
https://github.com/cocopon/atom-iceberg-syntax/issues/3

So I decided to create a new one and here is it:
https://github.com/cocopon/hyper-iceberg

And then, I noticed that npm package `hyper-iceberg` has already been published by you! But it seems that it has not been maintained recently. So, could you consider to transfer the ownership of the package to me? I'll add a credit of your name to README.

**Comment by flxy0** [comment]
@cocopon 
Hey there,
thank you so much for the wonderful theme.
I just gave you ownership of the package on NPM and removed myself from the owners. You should now be able to publish your version :)

I'll also add a deprecation message to the readme on here and link to your offical version just in case. Thanks for reaching out! :)

**Comment by cocopon** [comment]
@1se Thank you so much!

I succeeded to publish the new version. And added your name to README:
https://github.com/cocopon/hyper-iceberg/blob/master/README.md#special-thanks
